-- Seed marketplace data from mock files
-- Run this after marketplace-schema.sql

-- Clear existing data
TRUNCATE public.news, public.jobs;

-- ===== Seed News Data =====
INSERT INTO public.news (
  id, title, type, date, author, byline, views, excerpt, image, department, location, domain, theme, tags, "readingTime", "newsType", "newsSource", "focusArea", content
) VALUES
-- Original mock data
('leadership-principles', 'Leadership Principles | What''s Your Leadership Superpower?', 'Thought Leadership', '2024-08-19', 'Leads', 'Stephanie Kioko', 47, 'Researchers have identified more than 1,000 leadership traits, but only a handful consistently drive real impact…', null, 'Stories', 'Remote', null, 'Leadership', ARRAY['Playbook', 'EJP'], '10–20', 'Digital Tech News', 'DQ Leadership', 'Culture & People', 'Researchers have identified more than 1,000 leadership traits, but only a handful consistently drive real impact. This deep dive explores the core leadership principles that separate high-performing teams from the rest. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('dq-storybook-live', 'From Vision to Impact: The DQ Storybook Goes Live!', 'Announcement', '2024-08-14', 'DQ Communications', null, 75, 'We''re excited to announce that the DQ Story is now officially published on the DQ Competencies page…', null, 'Products', 'Dubai', 'Business', null, null, null, 'Corporate Announcements', 'DQ Communications', 'GHC', 'We''re excited to announce that the DQ Story is now officially published on the DQ Competencies page. This milestone represents months of collaborative work across all studios to codify our shared vision, values, and delivery principles. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('dq-persona-mindset', 'DQ Persona | Not Just a Role – It''s a Qatalyst Mindset', 'Thought Leadership', '2024-08-12', 'DQ Associates', 'Stephanie Kioko', 55, 'Culture eats strategy for breakfast—why a Qatalyst mindset matters for how we work and deliver…', null, 'Stories', 'Remote', null, 'Culture', ARRAY['QMS'], '5–10', 'Events & Campaigns', 'DQ Leadership', 'Culture & People', 'Culture eats strategy for breakfast—why a Qatalyst mindset matters for how we work and deliver. The DQ Persona isn''t just about what we do; it''s about how we think, collaborate, and approach every challenge with curiosity and craft. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('growth-emotional-intelligence', 'Grounded in Growth and Emotional Intelligence', 'Thought Leadership', '2024-08-08', 'Leads', 'Stephanie Kioko', 79, 'People with a Growth Mindset are twice as likely to take on challenges and push through obstacles…', null, 'Intelligence', 'Dubai', null, 'Leadership', ARRAY['EJP', 'Playbook'], '10–20', 'Digital Tech News', 'DQ Leadership', 'Culture & People', 'People with a Growth Mindset are twice as likely to take on challenges and push through obstacles. This research-backed approach to emotional intelligence and continuous learning forms the foundation of how we develop talent and build resilient teams. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('one-vision', 'The One Vision We All Build Toward', 'Thought Leadership', '2024-08-04', 'Partners', 'Stephanie Kioko', 50, 'At DQ, we all share a single powerful vision that guides how we build and deliver value…', null, 'Solutions', 'Remote', null, 'Delivery', ARRAY['Playbook', 'QMS'], '5–10', 'Product / Project Updates', 'DQ Leadership', 'GHC', 'At DQ, we all share a single powerful vision that guides how we build and deliver value. This unified direction ensures every project, every decision, and every innovation contributes to our collective impact. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('life-transactions', 'DQ''s Path to Perfect Life Transactions', 'Thought Leadership', '2024-08-01', 'Leads', 'Stephanie Kioko', 49, 'Every day we make thousands of transactions—here''s how we design for clarity and flow…', null, 'Delivery — Deploys', 'Remote', null, 'DTMF', ARRAY['QMS', 'EJP'], '10–20', 'Product / Project Updates', 'DQ Operations', 'GHC', 'Every day we make thousands of transactions—here''s how we design for clarity and flow. From digital interfaces to human interactions, our approach to transaction design prioritizes user experience and operational efficiency. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('agile-way-week', 'Your Week, the Agile Way', 'Thought Leadership', '2024-07-28', 'DQ Associates', 'Stephanie Kioko', 69, 'Practical ways to plan your week with agile habits—focus, alignment, and iterative delivery…', null, 'Delivery — Designs', 'Nairobi', null, 'Delivery', ARRAY['Playbook'], '<5', 'Events & Campaigns', 'DQ Operations', 'DWS', 'Practical ways to plan your week with agile habits—focus, alignment, and iterative delivery. This guide provides actionable frameworks for structuring your work cycles to maximize both productivity and team collaboration. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('riyadh-horizon-hub', 'Riyadh Horizon Hub Opens for Cross-Studio Delivery', 'Announcement', '2024-07-20', 'DQ Communications', null, 61, 'The new Riyadh Horizon Hub is live—bringing Delivery, Platform, and People teams together to accelerate Saudi programs.', null, 'Delivery — Deploys', 'Riyadh', 'Business', null, null, null, 'Corporate Announcements', 'DQ Leadership', 'GHC', 'The new Riyadh Horizon Hub is live—bringing Delivery, Platform, and People teams together to accelerate Saudi programs. This strategic expansion represents our commitment to local market expertise and cross-cultural collaboration. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('shifts-allocation-guidelines', 'Shifts Allocation Guidelines', 'Guidelines', '2024-07-25', 'DQ Communications', null, 58, 'New guidelines to enhance fairness and transparency for shifts allocation across teams…', null, 'DCO Operations', 'Dubai', 'People', null, null, null, 'Corporate Announcements', 'DQ Operations', 'DWS', 'New guidelines to enhance fairness and transparency for shifts allocation across teams. These updated procedures ensure equitable distribution of responsibilities while maintaining operational excellence. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('islamic-new-year', 'Honoring the Islamic New Year', 'Notice', '2024-06-27', 'DQ Communications', null, 63, 'A reflection on Al-Hijra 1447 AH—renewal, gratitude, and the values that ground our community…', null, 'HRA (People)', 'Dubai', 'People', null, null, null, 'Events & Campaigns', 'DQ Communications', 'Culture & People', 'A reflection on Al-Hijra 1447 AH—renewal, gratitude, and the values that ground our community. This sacred time reminds us of the importance of reflection, growth, and the shared values that unite our diverse team. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('dq-website-launch', 'DQ Corporate Website Launch!', 'Announcement', '2024-06-24', 'DQ Communications', null, 84, 'Our new DQ corporate website is live—packed with what makes DQ a leader in digital delivery…', null, 'Products', 'Remote', 'Technology', null, null, null, 'Corporate Announcements', 'DQ Communications', 'DWS', 'Our new DQ corporate website is live—packed with what makes DQ a leader in digital delivery. This comprehensive platform showcases our capabilities, culture, and commitment to excellence in every project we undertake. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('po-dev-sync-guidelines', 'Product Owner & Dev Sync Guidelines', 'Guidelines', '2024-06-19', 'DQ Communications', null, 70, 'Standardizing PO–Dev syncs for clarity, cadence, and decision-making across products…', null, 'DBP Delivery', 'Dubai', 'Operations', null, null, null, 'Product / Project Updates', 'DQ Operations', 'DWS', 'Standardizing PO–Dev syncs for clarity, cadence, and decision-making across products. These guidelines establish consistent communication patterns that enhance collaboration and accelerate delivery timelines. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('riyadh-designing-at-scale', 'Designing at Scale for Riyadh Citizen Services', 'Thought Leadership', '2024-06-15', 'Leads', 'Yara Al Harthy', 52, 'How the Riyadh studio co-created digital citizen services with local regulators—pairing delivery playbooks with cultural fluency.', null, 'Delivery — Designs', 'Riyadh', null, 'Delivery', ARRAY['Playbook', 'EJP'], '10–20', 'Product / Project Updates', 'DQ Operations', 'GHC', 'How the Riyadh studio co-created digital citizen services with local regulators—pairing delivery playbooks with cultural fluency. This case study demonstrates the power of combining technical excellence with deep cultural understanding. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('azure-devops-task-guidelines', 'Azure DevOps Task Guidelines', 'Guidelines', '2024-06-12', 'DQ Communications', null, 77, 'New task guidelines for ADO: naming, states, and flow so teams ship with less friction…', null, 'SecDevOps', 'Remote', 'Technology', null, null, null, 'Digital Tech News', 'DQ Operations', 'DWS', 'New task guidelines for ADO: naming, states, and flow so teams ship with less friction. These standardized practices streamline our development workflow and improve cross-team collaboration. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

('eid-al-adha', 'Blessed Eid al-Adha!', 'Notice', '2024-06-05', 'DQ Communications', null, 47, 'Warmest wishes to all observing Eid al-Adha—celebrating community and gratitude…', null, 'HRA (People)', 'Nairobi', 'People', null, null, null, 'Events & Campaigns', 'DQ Communications', 'Culture & People', 'Warmest wishes to all observing Eid al-Adha—celebrating community and gratitude. This blessed occasion reminds us of the importance of sacrifice, generosity, and the bonds that unite our global team. Since launching, DQ teams continue to connect dots across studios, squads, and journeys. Every announcement is an opportunity to reinforce a shared language, codify repeatable wins, and inspire new experiments. This story highlights the rituals, playbooks, and leadership behaviors that help teams deliver value faster—while keeping culture, clarity, and craft at the center. Read on for the context, quotes, and resources you can plug into right away.'),

-- New announcements
('company-wide-lunch-break-schedule', 'DQ CHANGES | COMPANY-WIDE LUNCH BREAK SCHEDULE', 'Announcement', '2024-08-20', 'Hi GOV', 'Corporate Comms', 0, 'Unified lunch break for all associates: 2:00 PM – 3:00 PM DXB Time. Please avoid meetings within this window (except emergencies).', null, null, 'Dubai', null, null, ARRAY['policy', 'schedule', 'collaboration'], '5–10', 'Corporate Announcements', 'DQ Communications', 'Culture & People', 'To enhance collaboration and synchronize workflows across all studios, we are implementing a unified company-wide lunch break schedule.

Effective immediately, the designated lunch break for all associates will be from 2:00 PM to 3:00 PM Dubai (DXB) Time.

This standardized schedule applies to all associates. The goal is to create a common window for breaks, ensuring seamless collaboration.

To support this initiative, we kindly ask for your cooperation:

All Associates: Please plan to take your lunch during this designated hour to ensure everyone is back online and available from 3:00 PM DXB Time.

Meeting Organizers: Please avoid scheduling meetings during the 2:00 PM - 3:00 PM DXB Time block to respect this common break period. An exception applies only for critical emergency meetings that cannot be scheduled at any other time.

Thank you for your cooperation in helping us build a more synchronized and efficient work environment.'),

('grading-review-program-grp', 'DQ ADP | GRADING REVIEW PROGRAM (GRP)', 'Announcement', '2024-08-20', 'Hi GOV', 'Corporate Comms', 0, 'Launch of the DQ Associate Grade Review Program to align associates to the SFIA-based grading scale; initial focus group led by Araba and Mercy Kyuma.', null, null, null, null, null, ARRAY['SFIA', 'grading', 'capability'], '10–20', 'Corporate Announcements', 'DQ Communications', 'Culture & People', '📢 DQ Associate Grade Review Program – Launch Announcement

Dear DQ Associates,

We are pleased to announce the launch of the DQ Associate Grade Review Program. This program aims to ensure all associates are aligned to the DQ SFIA-based grading scale, reflecting both their competence levels and scope of responsibility.

The review will be led by Araba and Mercy Kyuma, beginning with an initial focus group of about 10 associates before expanding to cover all associates across DQ. Associates included in the initial phase will be contacted directly, and broader communication will follow as the program scales up.

PS: Grading reviews involve Level Confirmation, Upgrade, or in rare cases a downgrade for better Learning and Development for the associate and the organization.

Purpose:
To maintain transparent, fair, and consistent grading standards across the organization, aligned with capability growth and performance.

More details will follow as we progress — stay tuned through this channel for updates!'),

('dq-storybook-latest-links', 'DQ Storybook — Latest Version and Links', 'Announcement', '2024-08-20', 'DQ Communications', null, 0, 'Explore the latest DQ Storybook and quick links to GHC elements including Vision, HoV, Persona, Agile TMS/SoS/Flows, and 6xD.', null, null, null, 'Business', null, ARRAY['story', 'GHC', 'references'], '5–10', 'Corporate Announcements', 'DQ Communications', 'GHC', 'Here''s the latest version of the DQ Storybook — our evolving narrative that brings the Golden Honeycomb of Competencies (GHC) to life. We''re continuing to shape and refine this Storybook, so keep an eye out for new updates and deep dives in the coming weeks.

DQ Storybook: Link

For quick reference, here are the current links to each element:
01. DQ Vision (Purpose) - Link
02. DQ HoV (Culture) - Link
03. DQ Persona (Identity) - Link
04. Agile TMS (Tasks) - Link
05. Agile SoS (Governance) - Link
06. Agile Flows (Value Streams) - Link
07. Agile 6xD (Products) : Link TBU');

-- ===== Seed Jobs Data =====
INSERT INTO public.jobs (
  id, title, department, "roleType", location, type, seniority, "sfiaLevel", summary, description, responsibilities, requirements, benefits, "postedOn", "applyUrl", image
) VALUES
('senior-frontend-developer', 'Senior Frontend Developer', 'Products', 'Tech', 'Dubai', 'Full-time', 'Senior', 'L4', 'Join our Products team to build cutting-edge user interfaces for DQ''s digital platforms.', 'We are looking for a Senior Frontend Developer to join our Products team in Dubai. You will be responsible for creating exceptional user experiences across our digital platforms.', ARRAY['Develop responsive web applications using React and TypeScript', 'Collaborate with designers and backend developers', 'Implement modern UI/UX patterns', 'Optimize applications for performance'], ARRAY['5+ years of frontend development experience', 'Expert knowledge of React, TypeScript, and modern CSS', 'Experience with state management libraries', 'Strong understanding of web performance optimization'], ARRAY['Competitive salary and benefits', 'Professional development opportunities', 'Flexible working arrangements', 'Health insurance'], '2024-08-15', 'https://careers.dq.com/apply/senior-frontend-developer', null),

('product-designer', 'Product Designer', 'Delivery — Designs', 'Design', 'Remote', 'Full-time', 'Mid-level', 'L3', 'Shape the future of digital experiences with our design team.', 'We are seeking a talented Product Designer to join our Delivery — Designs team. You will work on diverse projects across multiple industries.', ARRAY['Create user-centered design solutions', 'Conduct user research and usability testing', 'Collaborate with cross-functional teams', 'Maintain design systems and guidelines'], ARRAY['3+ years of product design experience', 'Proficiency in Figma and design tools', 'Strong portfolio demonstrating UX/UI skills', 'Experience with design systems'], ARRAY['Remote-first culture', 'Learning and development budget', 'Flexible working hours', 'Annual team retreats'], '2024-08-10', 'https://careers.dq.com/apply/product-designer', null),

('devops-engineer', 'DevOps Engineer', 'SecDevOps', 'Tech', 'Nairobi', 'Full-time', 'Mid-level', 'L3', 'Build and maintain our cloud infrastructure and deployment pipelines.', 'Join our SecDevOps team to help scale our infrastructure and improve our deployment processes across all DQ projects.', ARRAY['Design and implement CI/CD pipelines', 'Manage cloud infrastructure on AWS/Azure', 'Implement security best practices', 'Monitor and optimize system performance'], ARRAY['3+ years of DevOps experience', 'Experience with containerization (Docker, Kubernetes)', 'Knowledge of cloud platforms (AWS, Azure)', 'Scripting skills in Python or Bash'], ARRAY['Competitive salary package', 'Professional certifications support', 'Flexible working arrangements', 'Health and wellness benefits'], '2024-08-05', 'https://careers.dq.com/apply/devops-engineer', null),

('business-analyst', 'Business Analyst', 'Intelligence', 'Ops', 'Riyadh', 'Full-time', 'Mid-level', 'L3', 'Bridge the gap between business needs and technical solutions.', 'We are looking for a Business Analyst to join our Intelligence team in Riyadh, focusing on data-driven insights and process optimization.', ARRAY['Analyze business requirements and processes', 'Create detailed documentation and specifications', 'Facilitate stakeholder meetings and workshops', 'Support project delivery and change management'], ARRAY['3+ years of business analysis experience', 'Strong analytical and problem-solving skills', 'Experience with process mapping and documentation', 'Excellent communication skills in English and Arabic'], ARRAY['Relocation assistance available', 'Professional development opportunities', 'Comprehensive health insurance', 'Annual performance bonuses'], '2024-07-30', 'https://careers.dq.com/apply/business-analyst', null),

('hr-specialist', 'HR Specialist', 'HRA (People)', 'HR', 'Dubai', 'Full-time', 'Junior', 'L2', 'Support our people operations and help build a great workplace culture.', 'Join our HRA (People) team to support various HR functions including recruitment, employee relations, and organizational development.', ARRAY['Support recruitment and onboarding processes', 'Assist with employee relations and engagement', 'Maintain HR records and documentation', 'Support learning and development initiatives'], ARRAY['2+ years of HR experience', 'Knowledge of UAE labor law', 'Strong interpersonal and communication skills', 'Experience with HRIS systems'], ARRAY['Career growth opportunities', 'Professional HR certifications support', 'Flexible working arrangements', 'Comprehensive benefits package'], '2024-07-25', 'https://careers.dq.com/apply/hr-specialist', null);
