/**
 * Supabase Database Types
 * 
 * This file is auto-generated by Supabase CLI.
 * To regenerate: supabase gen types typescript --project-id your_project_id > src/types/database.types.ts
 * 
 * For now, this is a placeholder. Replace with actual generated types after running the Supabase CLI command.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      lms_courses: {
        Row: {
          id: string;
          slug: string;
          title: string;
          provider: string;
          course_category: string;
          delivery_mode: 'Video' | 'Guide' | 'Workshop' | 'Hybrid' | 'Online';
          duration: 'Bite-size' | 'Short' | 'Medium' | 'Long';
          level_code: 'L0' | 'L1' | 'L2' | 'L3' | 'L4' | 'L5' | 'L6' | 'L7' | 'L8';
          department: string[];
          locations: string[];
          audience: ('Associate' | 'Lead')[];
          status: 'live' | 'coming-soon';
          summary: string;
          highlights: string[];
          outcomes: string[];
          course_type: 'Course (Single Lesson)' | 'Course (Multi-Lessons)' | 'Course (Bundles)' | null;
          track: string | null;
          rating: number | null;
          review_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_courses']['Row'], 'created_at' | 'updated_at' | 'review_count'>;
        Update: Partial<Database['public']['Tables']['lms_courses']['Insert']>;
      };
      lms_reviews: {
        Row: {
          id: string;
          course_id: string;
          author: string;
          role: string;
          text: string;
          rating: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_reviews']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['lms_reviews']['Insert']>;
      };
      lms_case_studies: {
        Row: {
          id: string;
          course_id: string;
          title: string;
          description: string;
          link: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_case_studies']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['lms_case_studies']['Insert']>;
      };
      lms_references: {
        Row: {
          id: string;
          course_id: string;
          title: string;
          description: string;
          link: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_references']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['lms_references']['Insert']>;
      };
      lms_faqs: {
        Row: {
          id: string;
          course_id: string;
          question: string;
          answer: string;
          order_index: number;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_faqs']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['lms_faqs']['Insert']>;
      };
      lms_curriculum_items: {
        Row: {
          id: string;
          course_id: string;
          title: string;
          description: string | null;
          duration: string | null;
          order_index: number;
          is_locked: boolean;
          course_slug: string | null;
          parent_item_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_curriculum_items']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['lms_curriculum_items']['Insert']>;
      };
      lms_curriculum_topics: {
        Row: {
          id: string;
          curriculum_item_id: string;
          title: string;
          description: string | null;
          duration: string | null;
          order_index: number;
          is_locked: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_curriculum_topics']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['lms_curriculum_topics']['Insert']>;
      };
      lms_curriculum_lessons: {
        Row: {
          id: string;
          curriculum_item_id: string | null;
          curriculum_topic_id: string | null;
          title: string;
          description: string | null;
          duration: string | null;
          lesson_type: 'video' | 'guide' | 'quiz' | 'workshop' | 'assignment' | 'reading';
          order_index: number;
          is_locked: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lms_curriculum_lessons']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['lms_curriculum_lessons']['Insert']>;
      };
    };
    Views: {
      lms_courses_with_reviews: {
        Row: {
          // Add view columns here
        };
      };
      lms_curriculum_flat: {
        Row: {
          // Add view columns here
        };
      };
    };
    Functions: {
      // Add functions here
    };
    Enums: {
      lms_delivery_mode: 'Video' | 'Guide' | 'Workshop' | 'Hybrid' | 'Online';
      lms_duration: 'Bite-size' | 'Short' | 'Medium' | 'Long';
      lms_level_code: 'L0' | 'L1' | 'L2' | 'L3' | 'L4' | 'L5' | 'L6' | 'L7' | 'L8';
      lms_audience_type: 'Associate' | 'Lead';
      lms_course_status: 'live' | 'coming-soon';
      lms_course_type: 'Course (Single Lesson)' | 'Course (Multi-Lessons)' | 'Course (Bundles)';
      lms_lesson_type: 'video' | 'guide' | 'quiz' | 'workshop' | 'assignment' | 'reading';
    };
  };
}

